### ISSUE TITLE
MariaDB Configuration

### ISSUE THREAD

**Issue by smfsh** [DrupalStand/drupal-dev-docker#48]
The handcrafted maria db contaienr isnt reading the map.cnf file most likely because the default alpine install doesn't know to look for extra cnf files like the official docker images do. We need to either switch to an official image or rework the configuration for the db container.

tldr, drupal breaks hard because max packet size is 1mb by default.

**Comment by jackinloadup** [comment]
Should be fixed in #50. Close if you agree.

**Comment by smfsh** [comment]
Issue was actually not fixed, but rectified by removing the custom maria container altogether and going with the community maintained one. Additional changes were made in df8f600fbc3de3f92099fdf1155302060ce956eb
